GET http://localhost:3000/subscriptions/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiIxc2FtdWVsaHVydGFkbzIwQGdtYWlsLmNvbSIsImlhdCI6MTY1Mzk2MjI2MiwiZXhwIjoxNjUzOTg3NDYyfQ.vE3jmQxCGXYIaSc6mjHiW9R_Rx4IsUBesALeWUG1fgA
content-type: application/json